-- DL 3

SELECT E.ENAME "EMPLOYEE NAME", D.DNAME "DEPARTMENT NAME"
FROM EMP E JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO
WHERE UPPER(JOB) = 'SALESMAN' OR UPPER(JOB) = 'ANALYST';

--

SELECT E.ENAME , E.ENAME || ' works in ' || D.DNAME "DEPARTMENT NAME"
FROM EMP E JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO;

--

SELECT D.DNAME "DEPARTMENT",E.JOB,MAX(E.SAL) "HIGHEST SALARY"
FROM EMP E JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO
GROUP BY D.DNAME, E.JOB
ORDER BY D.DNAME;

--

SELECT E.ENAME "EMPLOYEE NAME", D.DNAME "DEPARTMENT", D.LOC "LOCATION", E.JOB
FROM EMP E JOIN DEPT D
ON E.DEPTNO=D.DEPTNO
WHERE UPPER(E.JOB)='MANAGER' AND E.SAL>2900;

--

SELECT E1.ENAME "EMPLOYEES REPORTING TO KING"
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
WHERE UPPER(E2.ENAME) = 'KING';

--

SELECT COUNT(*) "COUNT OF EMPLOYEES REPORTING TO KING"
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
WHERE UPPER(E2.ENAME) = 'KING';

--

SELECT 'The Manager of ' || E1.ENAME || ' is ' || E2.ENAME "Manager Names"
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO
ORDER BY E1.EMPNO;

--

select * from flights;
select * from customers;

--

SELECT C.CUSTNAME
FROM CUSTOMERS C JOIN FLIGHTS F
ON C.FLIGHTNO = F.FLIGHTNO
WHERE UPPER(F.STATUS)='DEPARTURE ON TIME';

--

SELECT C.CUSTNAME
FROM CUSTOMERS C JOIN FLIGHTS F
ON C.FLIGHTNO = F.FLIGHTNO
WHERE UPPER(F.ROUTE)<>'PUNE-BANGALORE';

--

SELECT C.CUSTNAME
FROM CUSTOMERS C JOIN FLIGHTS F
ON C.FLIGHTNO = F.FLIGHTNO
WHERE UPPER(F.GATENO)='G1';

--

SELECT C.CUSTNAME
FROM CUSTOMERS C JOIN FLIGHTS F
ON C.FLIGHTNO = F.FLIGHTNO
WHERE UPPER(F.ROUTE)='PUNE-CHANDIGAD' AND UPPER(F.FLIGHTNAME)='KING FISHER';

--

select * from CUSTOMER_DETAILS;
select * from PAYMENT_DETAILS;

--

SELECT C.CUSTID, C.CNAME, P.AMOUNT, 
CASE
WHEN C.CUSTID=P.CUSTID THEN 'Customer Present in Payment_Details'
ELSE 'Customer Absent in Payment_Details'
END "REMARK"
FROM CUSTOMER_DETAILS C LEFT JOIN PAYMENT_DETAILS P
ON C.CUSTID=P.CUSTID;

-- ANSI 92

SELECT 
E.EMPLOYEE_ID, 
E.FIRST_NAME || ' ' || E.LAST_NAME "EMPLOYEE NAME", 
E.DEPARMENT_ID, 
D.DEPARTMENT_NAME,
H.START_DATE,
H.END_DATE,
J.JOB_TITLE,
C.COUNTRY_NAME,
R.REGION_NAME,
J.MAX_SALARY - E.SALARY "DIFFERENCE MAXIMUM SALARY AND EMPLOYEE SALARY"
FROM EMPLOYEES E 
JOIN DEPARTMENTS D ON E.DEPARMENT_ID=D.DEPARTMENT_ID
JOIN JOB_HISTORY H ON E.EMPLOYEE_ID=H.EMPLOYEE_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C ON L.COUNTRY_ID= C.COUNTRY_ID
JOIN REGIONS R ON C.REGIOD_ID = R.REGION_ID;

-- ANSI 89

SELECT 
E.EMPLOYEE_ID, 
E.FIRST_NAME || ' ' || E.LAST_NAME "EMPLOYEE NAME", 
E.DEPARMENT_ID, 
D.DEPARTMENT_NAME,
H.START_DATE,
H.END_DATE,
J.JOB_TITLE,
C.COUNTRY_NAME,
R.REGION_NAME,
J.MAX_SALARY - E.SALARY "DIFFERENCE MAXIMUM SALARY AND EMPLOYEE SALARY"
FROM EMPLOYEES E, DEPARTMENTS D, JOB_HISTORY H, JOBS J, LOCATIONS L, COUNTRIES C , REGIONS R
WHERE 
E.DEPARMENT_ID=D.DEPARTMENT_ID AND 
E.EMPLOYEE_ID=H.EMPLOYEE_ID AND
E.JOB_ID = J.JOB_ID AND
D.LOCATION_ID = L.LOCATION_ID AND
L.COUNTRY_ID= C.COUNTRY_ID AND
C.REGIOD_ID = R.REGION_ID;