SELECT * 
FROM EMPLOYEES
WHERE HIRE_DATE < TO_DATE('1982', 'YYYY');

--

SELECT ENAME, SAL,  TO_CHAR(HIREDATE, 'DD-MON-YY') "Default",  TO_CHAR(HIREDATE, 'MM/DD/YY') "AMERICAN",  TO_CHAR(HIREDATE, 'DD-MM-YY') "INDIAN"
FROM EMP;

SELECT TO_CHAR(HIREDATE,'YY') "YEAR", MAX(SAL)
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YY')
ORDER BY 1;

SELECT ENAME || ' is joined in the year ' || TO_CHAR(HIREDATE,'YY') "YEAR OF JOINING"
FROM EMP;

SELECT INITCAP(ENAME) || ' joined on ' || INITCAP(TO_CHAR(HIREDATE,'DAY')) "JOINING DAY"
FROM EMP;

SELECT * 
FROM EMP
WHERE JOB NOT IN ('MANAGER', 'PRESIDENT') AND TRIM(TO_CHAR(TO_DATE(HIREDATE),'DAY')) NOT IN ('MONDAY', 'FRIDAY');

